### PR TITLE
snapd: update to 2.31.1, add python-docutils to makedepends, drop snap-seccomp patches

### PR DESCRIPTION
**Pull request by bboozzoo**
New upstream release 2.31.1.

Add python-docutils to makedepends, so that man pages for snap-confine and
snap-discard-ns are generated (see #4 for more details).

Drop snap-seccomp patches. The upstream has dropped setting LDFLAGS for cgo
directly in cgo comment sections.

@aimileus @zyga take a look please

### CODE REVIEW

**Comment by emielwiedijk** [comment]
LGTM, I currently don't have acces to my computer, so please just push to snapd as well.

**Comment by bboozzoo** [comment]
Sure, will do.

**Comment by emielwiedijk** [comment]
Thanks!

**Comment by bboozzoo** [comment]
Pushed https://aur.archlinux.org/cgit/aur.git/commit/?h=snapd&id=7a7b503350054d557167e3872765d8af04308d3f

**Pull request merged**
